doorlock@raspberrypi:~ $ sudo python3 face_recog.py
Traceback (most recent call last):
  File "/home/doorlock/face_recog.py", line 3, in <module>
    import face_recognition
ModuleNotFoundError: No module named 'face_recognition'
doorlock@raspberrypi:~ $ python3 face_recog.py
mmal: mmal_vc_port_enable: failed to enable port vc.null_sink:in:0(OPQV): ENOSPC
mmal: mmal_port_enable: failed to enable connected port (vc.null_sink:in:0(OPQV))0x670bcb0 (ENOSPC)
mmal: mmal_connection_enable: output port couldn't be enabled
Traceback (most recent call last):
  File "/home/doorlock/face_recog.py", line 103, in <module>
    face_recog = FaceRecog()
  File "/home/doorlock/face_recog.py", line 16, in __init__
    self.camera = picamera.PiCamera()
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 433, in __init__
    self._init_preview()
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 512, in _init_preview
    self._preview = PiNullSink(
  File "/usr/lib/python3/dist-packages/picamera/renderers.py", line 558, in __init__
    self.renderer.inputs[0].connect(source).enable()
  File "/usr/lib/python3/dist-packages/picamera/mmalobj.py", line 2210, in enable
    mmal_check(
  File "/usr/lib/python3/dist-packages/picamera/exc.py", line 184, in mmal_check
    raise PiCameraMMALError(status, prefix)
picamera.exc.PiCameraMMALError: Failed to enable connection: Out of resources
Exception ignored in: <function FaceRecog.__del__ at 0x657d0190>
Traceback (most recent call last):
  File "/home/doorlock/face_recog.py", line 40, in __del__
    self.camera.close()
AttributeError: 'FaceRecog' object has no attribute 'camera'
